### ISSUE TITLE
Add Uganda scraper

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#121]
~~The new pipeline has several benefits we want; better filenames, error logs, not hitting API end points twice sometimes ...~~

**Comment by odscjames** [comment]
On hold, see CRM 5332

**Comment by jpmckinney** [comment]
I think the CRM issue indicates that we can try new API endpoint (the fact that it 500s sometimes shouldn't be a blocker, as other APIs are also unstable).

I don't see much immediate similarity between the APIs. Since it's the last "old pipeline" scraper, I'm removing it, so that we can remove the old pipeline code.

For reference, the last version of the old scraper is https://github.com/open-contracting/kingfisher-scrape/blob/fffbde8/kingfisher_scrapy/spiders/uganda.py

**Comment by jpmckinney** [comment]
See issue about old scraper if relevant: #85
