### ISSUE TITLE
Add Georgia scraper (old website)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#155]
Georgia has this older data source: http://opendata.spa.ge/#/tenders (Click English top-left)

When I tried, the "All tenders in zip file" expands 67784 files in annual folders from 2010 to 2017, almost all of which are 0 bytes.

However, the individual JSON links work. Not sure if this is considered blocked or not.

**Comment by odscjames** [comment]
Bit clunky this, but the website is a modern Javascript framework and it's easy to get the URL that returns the results to that page:

eg http://opendata.spa.ge/aj_tenders_list_angular?page=27810&sort=1&lang=eng

You can then make the URL of the JSON by 

    http://opendata.spa.ge/json/Tenders/<json_field>/<REGNUMBER>.json

There really is a lot of data here - 27817 pages, 10 entries per page so that's 300K requests to make.

However, I just checked and the ZIp option now seems to be working, so that might be better. A more stable API to work against.

**Comment by robredpath** [comment]
@odscjames this seems to have fallen through some gaps - it's not linked to a Trello card but we seem to have done some work on it - and there's a merged PR! What's the status of this?

**Comment by jpmckinney** [comment]
Pinging re: issue status.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Georgia scraper (old website)](https://trello.com/c/OqLKppxm/82-add-georgia-scraper-old-website)

**Comment by odscjames** [comment]
Found the Trello card and linked. I think this issue is now done - https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/spiders/georgia_opendata.py is in master?

**Comment by jpmckinney** [comment]
Yup, done!
