### ISSUE TITLE
Users see errors when cloning repo and installing reqs

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-scrape#206]
```
!git clone https://github.com/open-contracting/kingfisher-scrape.git > kingfisher_git_log.txt
!cd kingfisher-scrape; pip install -r requirements_dev.txt > kingfisher_log.txt
!FILES_STORE='data'
```
```
Cloning into 'kingfisher-scrape'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1333 (delta 30), reused 35 (delta 20), pack-reused 1268
Receiving objects: 100% (1333/1333), 273.55 KiB | 10.52 MiB/s, done.
Resolving deltas: 100% (908/908), done.
ERROR: kaggle 1.5.6 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.6 which is incompatible.
ERROR: google-colab 1.0.0 has requirement requests~=2.21.0, but you'll have requests 2.22.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
```

**Comment by jpmckinney** [comment]
Hmm, I could not reproduce on a fresh virtualenv. Was this run in a fresh virtualenv, or in an existing one (or perhaps in no virtualenv)? If the latter, then it's possible that packages that were previously installed are causing conflicts.

**Comment by odscjames** [comment]
This was in the context of running via Colab for training materials. "then it's possible that packages that were previously installed are causing conflicts." is probably the cause. We need to see what we can do.

**Comment by jpmckinney** [comment]
I'm not sure why Kingfisher Scrape would be installed in Colaboratory. It's to be used as an application, not as a library, which means it uses fixed versions in requirements.txt – which are likely to cause conflicts.

Without knowing anything about the user(s), I'd say the solution is to install with `pip install -r requirements.in` instead of requirements.txt. As we have no way of conveying this information to the unidentified user, I'll close, as I don't anticipate much use of this repo in Colaboratory.

Feel free to communicate with the users directly if they are known.
