### ISSUE TITLE
paraguay_base/hacienda: Implementation questions / review

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-scrape#323]
* Why is it necessary to call `self.crawler.engine.crawl`? Can we add a code-level comment?
* The 2nd `logger` line for "Requesting access token…" should be inside the `else` branch
* paraguay_hacienda includes the `clientSecret` value. Should this be kept secret, and provided as a spider argument instead?

**Comment by yolile** [comment]
> Why is it necessary to call self.crawler.engine.crawl? Can we add a code-level comment?

it is necessary because that method is called througth a spider start_request or parse method, or other method where the request it is send to the scrapy request queue, so if we yield the request instead the request is never called.  With `self.crawler.engine.crawl` the request it is inserted in the queue and be called.

> paraguay_hacienda includes the clientSecret value. Should this be kept secret, and provided as a spider argument instead?

This is actually a enviroment variable already, but I noticed that it is also hardcoded in one line, we should change that

@aguilerapy please update paraguay_base and paraguay_hacienda with the suggested changes

**Comment by jpmckinney** [comment]
I did a quick search for other Scrapy Oauth work, and there are a few middlewares mentioned in this thread: https://groups.google.com/forum/#!msg/scrapy-users/EUzuuy6oaeE/7tmZBsJLDAAJ

They use downloader middlewares instead, in order to intercept the requests. For example: https://github.com/scrapy/scrapy/compare/master...juanriaza:oauth-draft?expand=1

This might be a more correct use of Scrapy than calling `crawler.engine.crawl` directly.

**Comment by aguilerapy** [comment]
@jpmckinney I think those solutions aren't for our case because the token for Paraguay can expire. Therefore, we use `crawler.engine.crawl` because we must stop and send an "new valid token" request for a new token when it expires, with `crawler.engine.crawl` the request is inserted into the queue and called immediately, so the scraper continues where it stops with the new token.

We use download middlewares to intercept the requests and add the token with `request.headers ['Authorization'] = spider.access_token`, similar to the other Scrapy Oauth work, but now I delete the call to `crawler.engine.crawl`.

What I did is modify our `process_request()` in ParaguayAuthMiddleware class:

1. Save the last request that has the expired token or doesn't have a token yet (the first time).
2. Return that "emergency" request in `process_request()` with `return spider.request_access_token()`
3. Continue scraping where it stops after obtaining the new token with `yield self.last_request` (calling the last saved request) in `parse_access_token()`

**Comment by jpmckinney** [comment]
Ah, you're right – the linked code doesn't handle `oauthlib.oauth2.TokenExpiredError`, which would be raised in our case if we were to use `oauthlib` and set `expires_at`.

There is a `requests-oauthlib` library, but I can't find one for Twisted or Scrapy. I searched for OAuth and Twisted/Scrapy again, and only found ([long](https://stackoverflow.com/questions/29712644/how-to-use-twisted-to-check-gmail-with-oauth2-0-authentication)) StackOverflow answers, whereas I'd prefer a library. Since no one has a better solution that we can rely on, we can continue to use `crawler.engine.crawl` – which is much simpler than going one layer down and interacting with Twisted directly.
