### ISSUE TITLE
Portugal scraper fails to post to kingfisher-process

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-scrape#354]
Probably due to the size of the downloaded file? (~500mb compressed, ~4gb flat)

Some of the logs from the server:

* http://scrape.kingfisher.open-contracting.org/logs/kingfisher/portugal/94e9d76475de11ea96750c9d92c523cb.log
* http://scrape.kingfisher.open-contracting.org/logs/kingfisher/portugal/3c1f82b075ec11ea96750c9d92c523cb.log

From https://github.com/open-contracting/kingfisher-scrape/issues/348#issuecomment-610538959.

**Comment by jpmckinney** [comment]
Hmm, some Digiwhist files are bigger, so I don't think it's only the size.

**Comment by odscjames** [comment]
Digiwhist are different tho. Scrape downloads the one file, then extracts it, then the contents are sent a line at a time to Process. So Process does not get large data.

Portugal extracts a 4GB file then attempts to send it to Process in one API request. I'm writing this quickly before meeting so I haven't checked server logs but we have seen this before and I'm 99% certain the problem here is that when Python attempts to open a 4GB JSON file in memory in one go, it's to large. The current UWSGI limit is 2GB.

We did discuss this issue before #154. The real answer is something like :  

When the Process API gets sent a file, it should not attempt to process it straight away. Rather, it should save it to disk/db and return a result to the caller. Then it should send a message down a message queue and a worker at the other end can process it. Workers don't have resources limits on them like UWSGI does. That will also smooth out resources demand on Process and make for a more consistent load on the server.

The only fast answers we have are:
* to massively increase the limits on UWSGI server
* local load the data by hand

**Comment by jpmckinney** [comment]
As an intermediate solution, can't we also split the large file into smaller files, like we do with Digiwhist? Portugal is also JSON Lines.

**Comment by odscjames** [comment]
Oh, didn't know it was JSON lines. In that case yes, it seems pretty simple to read the file a line at a time on the Scrape side and send each line to process with the number parameter. See `kingfisher_scrapy/spiders/digiwhist_base.py`. If it wasn't JSON Lines I'd be concerned to get a robust method of splitting the file, but Python's readline() function will do it.

**Comment by jpmckinney** [comment]
In future, if we do need to parse concatenated JSON (that is not JSON Lines) or JSON arrays, then ijson can do it without consuming much memory. See my quick docs here: https://ocdskit.readthedocs.io/en/latest/library.html#input
