### ISSUE TITLE
Using spider arguments doesn't work

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-scrape#364]
I was trying to run OpenOpps spider with the date arguments, but it doesn't work for me, I tried: 

`curl http://localhost:6800/schedule.json -d project=kingfisher -d spider=openopps -d note="Started by Andres" -d from_date="2020-01-01"`

Locally I have no problems.

**Comment by jpmckinney** [comment]
Hmm, the logs don't report what spider arguments the spider received. Should we add something like this to `BaseSpider.__init__`?

```python
spider_arguments = {
    'sample': sample,
    'note': note,
    'from_date': from_date,
    'until_date': until_date,
}
spider_arguments.update(kwargs)
self.logger.info('Spider arguments: {!r}'.format(spider_arguments))
```

**Comment by aguilerapy** [comment]
Yes, I was thinking the same

**Comment by jpmckinney** [comment]
I think maybe the new spider just wasn't [deployed](https://ocdsdeploy.readthedocs.io/en/latest/use/kingfisher-collect.html#update-spiders-in-kingfisher-scrape). I had to commit a small fix in https://github.com/open-contracting/kingfisher-scrape/commit/38feef42def3b02b84c871aa35aa8c3bbdb99de4 because `scrapyd-deploy kingfisher` was erroring. I then ran:

```
curl -n http://scrape.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=openopps -d note="Started by James" -d from_date="2020-04-24"
```

And I see in the log: 

```
2020-04-24 19:43:19 [openopps] INFO: Spider arguments: {'sample': None, 'note': 'Started by James', 'from_date': '2020-04-24', 'until_date': None, '_job': '1529d6e8865311eab08a0c9d92c523cb'}
```
