### ISSUE TITLE
Using Scrapy with Paraguay's API

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-scrape#41]
Paraguay's OCDS data is accessible through an API as documented [here](https://www.contrataciones.gov.py/datos/api/v2/).

An access token is required to making requests against the API. The access token is valid for 5000 request or 15 minutes, after which a new access token has to be negotiated. The current approach of using the `FilesPipeline` to download JSON files makes impossible to manage the access key cycle, since Scrapy manages the file downloads when using `FilesPipeline`.

I propose the following approach for Paraguay's scraper:

1. Download JSON contents in the spider. Manage access key generation there; probably it would be necessary to disable concurrency (only for this spider in particular).
2. Write an additional Item Pipeline that returns the same output as `KingfisherFilesPipeline`. The pipeline will receive the JSON payload and store it in files.
3. Set the logic needed for the pipeline from (2) to work with this spider only. 

Please comment with any alternatives or suggestions!

**Comment by jpmckinney** [comment]
My understanding is that, for Paraguay requests, if a request fails for authentication reasons, then it should recover by getting a new access token.

I haven't looked closely at Scrapy's implementation or at recommended approaches, but my assumption is that we can subclass the `Response` and/or `Request` objects to do the above. I'm not sure where those classes get instantiated (in order to swap in our subclasses), but I figure there's a pattern we can follow, considering Scrapy suggests subclassing these (and already has some utility subclasses available).

**Comment by romifz** [comment]
That's right, when a request fails with a 401 code, a new access code can be negotiated before attempting a new request.

Extending `Request` or another class with similar purposes (like [`DownloaderMiddleware`](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#writing-your-own-downloader-middleware)) is an option as well. I am thinking on keeping the authentication logic in Paraguay's spider to minimise the risk of affecting other spiders, but it should be easy to restrict the extended class to use the access key logic with Paraguay's spider only.

**Comment by jpmckinney** [comment]
Is this closed / taken forward in #141?

**Comment by romifz** [comment]
Yes, closing the issue
