### ISSUE TITLE
Do we only ever return one URL in file_urls?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#51]
eg https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/spiders/afghanistan_records.py#L18

We currently do - so I've just written code that goes with that assumption.

If yes:

Can we document that in dev docs as a rule?
Also I think that means we can remove some for loops from pipelines to simplify it - I can try that?

If not:

We'll document that too and I'll try and find a fix to code that assumes that

**Comment by rhiaro** [comment]
If I understand correctly, it *should* always be possible to return one, and we *should* try to return one because downloads through the FilesPipeline are blocking, so basically it's faster if we send them through one at a time.

In a more normal Scrapy pipeline, there would be likely be multiple file downloads per 'item' (webpage), ie you get the Response from a URL and then find all the linked PDFs or images on a page and get them in one block. And then the pipeline gets held up there until they're all done.

But in our case, while there are spiders where we *could* request one API endpoint and get multiple URLs for JSON files back and send them all at once to the FilesPipeline, it's better to loop through them in the spider and pass one by one because of the way the whole pipeline gets held up. At least, I tried it both ways, and doing them one by one was faster.

This is noted in the [docs for Parse](https://kingfisher-scrape.readthedocs.io/en/latest/writing-scrapers.html#parse).

**Comment by odscjames** [comment]
New pipeline makes this not relevant any more.
