### ISSUE TITLE
Port indonesia_bandung Scraper

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-scrape#72]

**Comment by yolile** [comment]
The links seems to be broken: https://birms.bandung.go.id/beta/api/packages/year/2013 
should we port the scraper anyway?

**Comment by jpmckinney** [comment]
Seems to work if you remove /beta/

**Comment by yolile** [comment]
great!

**Comment by yolile** [comment]
Ok, so that service returns a list of releases, no release_package and currently none of our models support that https://kingfisher-process.readthedocs.io/en/latest/data-model.html#data-types-for-files

And the old url https://birms.bandung.go.id/api/packages/year/2013 it is not working anymore either
